<?php
/*
 *	Topspin Items Listing
 *
 *	Usage: [topspin_buy_buttons]
 *
 *	Available template variables
 *		storedata	(array)
 *		storeitems	(array)
 *
 *
 *	WARNING: DO NOT EDIT THIS FILE!
 *
 *	To edit the PHP, copy this file to your
 *	active theme's directory and edit from that
 *	new file.
 *
 *	Example: /wp-content/themes/<current-theme>/topspin-simplified/item-listings.php
 *
 */
?>

<?php if(count($storeitems)) : ?>
<div id="topspin-store-<?php echo $storedata['id'];?>" class="topspin-store">
<table class="topspin-simplified-item-listings">
	<?php for($row=1;$row<=ceil(count($storeitems)/$storedata['grid_columns']);$row++) : ?>
	<?php
	$mod = count($storeitems)%$storedata['grid_columns'];
	$diff = ($mod>0) ? $storedata['grid_columns']-$mod : 0;
	?>
	<tr class="topspin-item-title">
		<?php
		for($col=1;$col<=$storedata['grid_columns'];$col++) : $key = ($row*$storedata['grid_columns'])-($storedata['grid_columns']-($col-1)); ?>
		<td width="<?php echo floor(100/$storedata['grid_columns']);?>%">
			<?php if(isset($storeitems[$key])) : ?>
			<h2 class="topspin-title-name">
				<?php if($storeitems[$key]['created_date']>TOPSPIN_NEW_CUTOFF_DATE) : ?><span class="topspin-item-new">NEW</span><?php endif; ?>
				<a class="topspin-view-item" href="#!/<?php echo $storeitems[$key]['id']; ?>"><?php echo $storeitems[$key]['name'];?></a>
			</h2>
			<?php endif; ?>
		</td>
		<?php endfor; ?>
	</tr>
	<tr class="topspin-item-image">
		<?php
		for($col=1;$col<=$storedata['grid_columns'];$col++) : $key = ($row*$storedata['grid_columns'])-($storedata['grid_columns']-($col-1)); ?>
		<td width="<?php echo floor(100/$storedata['grid_columns']);?>%">
        	<?php ## BEGIN SWITCH OFFER TYPE
			$item = $storeitems[$key];
            switch($item['offer_type']) {
				case 'buy_button':
					if(isset($storeitems[$key])) : ?>
					<a class="topspin-view-item" href="#!/<?php echo $storeitems[$key]['id']; ?>"><img src="<?php echo $storeitems[$key]['default_image'];?>" /></a>
					<?php endif;
					break;
				case 'email_for_media':
				case 'bundle_widget':
				case 'single_track_player_widget': ?>
                	<div class="topspin-item-embed"><?php echo $item['embed_code'];?></div>
					<?php break;
			} ## END SWITCH OFFER TYPE
			?>
		</td>
		<?php endfor; ?>
	</tr>
	<tr class="topspin-item-desc">
		<?php for($col=1;$col<=$storedata['grid_columns'];$col++) : $key = ($row*$storedata['grid_columns'])-($storedata['grid_columns']-($col-1)); ?>
		<td>
			<?php if(isset($storeitems[$key])) : ?>
				<?php echo substr($storeitems[$key]['description'],0,$storedata['desc_length']); ?>
			<?php endif; ?>
		</td>
		<?php endfor; ?>
	</tr>
	<tr class="topspin-item-price">
		<?php
		for($col=1;$col<=$storedata['grid_columns'];$col++) : $key = ($row*$storedata['grid_columns'])-($storedata['grid_columns']-($col-1)); ?>
		<td width="<?php echo floor(100/$storedata['grid_columns']);?>%">
		<?php if(isset($storeitems[$key])) : ?>
			<?php if($storeitems[$key]['tag_name']==$storedata['sale_tag']) : ?><div class="topspin-item-onsale">ON SALE!</div><?php endif; ?>
			Price: <?php echo $storeitems[$key]['symbol'];?><?php echo $storeitems[$key]['price'];?>
		<?php endif; ?>
		</td>
		<?php endfor; ?>
	</tr>
	<tr class="topspin-item-buy">
		<?php
		for($col=1;$col<=$storedata['grid_columns'];$col++) : $key = ($row*$storedata['grid_columns'])-($storedata['grid_columns']-($col-1)); ?>
		<td width="<?php echo floor(100/$storedata['grid_columns']);?>%">
		<?php if(isset($storeitems[$key])) : ?>
			<?php if($storeitems[$key]['in_stock_quantity']>0 || $storeitems[$key]['product_type']=='digital_package') : ?>
				<a class="topspin-buy" href="<?php echo $storeitems[$key]['offer_url'];?>">Buy</a>
			<?php else : ?>
				<span class="topspin-soldout">SOLD OUT</span>
			<?php endif; ?>
		<?php endif; ?>
		</td>
		<?php endfor; ?>
	</tr>
	<tr class="topspin-spacer"><td colspan="<?php echo $storedata['grid_columns'];?>"></td></tr>
	<?php endfor; ?>
</table>

<?php ## BEGIN PAGINATION
if(!$storedata['show_all_items'] && $storedata['curr_page']<=$storedata['total_pages'] && $storedata['total_pages']>1) { ?>
   	<div class="topspin-pagination">
   	Page <?php echo $storedata['curr_page'];?> of <?php echo $storedata['total_pages'];?>
	<?php if($storedata['prev_page']) : ?><a class="topspin-prev" href="<?php echo $storedata['prev_page'];?>">Previous</a><?php endif; ?>
	<?php if($storedata['next_page']) : ?><a class="topspin-next" href="<?php echo $storedata['next_page'];?>">Next</a><?php endif; ?>
	</div>
<?php } ## END PAGINATION ?>

</div>
<?php endif; ?>
